In [2]:
import pandas as pd

file_name = r'C:\Users\USER\Desktop\a找工作\作品集\預測模型\資料集\amazon_laptop_prices_v01.csv'
df=pd.read_csv(file_name)


#查看數據型態
print(df.info())

# 強制顯示所有欄位 (不隱藏中間欄位)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4446 entries, 0 to 4445
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 4446 non-null   object
 1   model                 3282 non-null   object
 2   screen_size           4417 non-null   object
 3   color                 3867 non-null   object
 4   harddisk              3870 non-null   object
 5   cpu                   4346 non-null   object
 6   ram                   4385 non-null   object
 7   OS                    4420 non-null   object
 8   special_features      2054 non-null   object
 9   graphics              4381 non-null   object
 10  graphics_coprocessor  2574 non-null   object
 11  cpu_speed             1520 non-null   object
 12  rating                2174 non-null   float64
 13  price                 4441 non-null   object
dtypes: float64(1), object(13)
memory usage: 486.4+ KB
None

   brand                  model   screen_size       color harddisk            cpu    ram               OS  special_features    graphics graphics_coprocessor cpu_speed  rating       price
0   ROKC                    NaN     14 Inches        Blue  1000 GB  Intel Core i7   8 GB       Windows 11               NaN  Integrated                Intel   1.2 GHz     NaN    $589.99
1     HP                    NaN   15.6 Inches      Silver  1000 GB  Intel Core i5  64 GB   Windows 11 Pro  Backlit Keyboard  Integrated                Intel       NaN     4.5    $999.99
2    MSI  Vector GP66 12UGS-267  15.66 Inches  Core Black      NaN  Intel Core i9  32 GB  Windows 11 Home               NaN   Dedicated                  NaN   1.8 GHz     5.0  $1,599.00
3  Apple            MacBook Air   13.3 Inches      Silver   256 GB        Unknown   8 GB           Mac OS  Backlit Keyboard  Integrated                  NaN       NaN     4.8    $689.99
4  Apple            MacBook Air   15.3 Inches    Midnight   256 GB        Unknown   8 GB           Mac OS               NaN  Integrated                  NaN       NaN     4.8  $1,144.48

In [3]:
#df['price']=df['price'].astype(str).str.replace('$','').str.replace(',','')

#先把貨幣符號提取出來
df['currency_symbol']=df['price'].astype(str).str.extract('([\$€£¥])')
# 看看你的符號欄位裡到底有哪些不同的東西
print(df['currency_symbol'].value_counts())
#只有美元符號，那可以全部移除掉
df['price']=df['price'].astype(str).str.replace('$','').str.replace(',','')
df['price']=pd.to_numeric(df['price'],errors='coerce')
df.head()

currency_symbol
$    4441
Name: count, dtype: int64

<>:4: SyntaxWarning: invalid escape sequence '\$'
<>:4: SyntaxWarning: invalid escape sequence '\$'
C:\Users\USER\AppData\Local\Temp\ipykernel_16356\1062163417.py:4: SyntaxWarning: invalid escape sequence '\$'
  df['currency_symbol']=df['price'].astype(str).str.extract('([\$€£¥])')

   brand                  model   screen_size       color harddisk            cpu    ram               OS  special_features    graphics graphics_coprocessor cpu_speed  rating    price currency_symbol
0   ROKC                    NaN     14 Inches        Blue  1000 GB  Intel Core i7   8 GB       Windows 11               NaN  Integrated                Intel   1.2 GHz     NaN   589.99               $
1     HP                    NaN   15.6 Inches      Silver  1000 GB  Intel Core i5  64 GB   Windows 11 Pro  Backlit Keyboard  Integrated                Intel       NaN     4.5   999.99               $
2    MSI  Vector GP66 12UGS-267  15.66 Inches  Core Black      NaN  Intel Core i9  32 GB  Windows 11 Home               NaN   Dedicated                  NaN   1.8 GHz     5.0  1599.00               $
3  Apple            MacBook Air   13.3 Inches      Silver   256 GB        Unknown   8 GB           Mac OS  Backlit Keyboard  Integrated                  NaN       NaN     4.8   689.99               $
4  Apple            MacBook Air   15.3 Inches    Midnight   256 GB        Unknown   8 GB           Mac OS               NaN  Integrated                  NaN       NaN     4.8  1144.48               $

In [4]:
#處理RAM
df['ram'].value_counts() #沒有TB，可以直接處理掉
df=df.rename(columns={'ram': 'ram(GB)'})
df['ram(GB)']=df['ram(GB)'].astype(str).str.extract('(\d+)')

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\USER\AppData\Local\Temp\ipykernel_16356\72206226.py:4: SyntaxWarning: invalid escape sequence '\d'
  df['ram(GB)']=df['ram(GB)'].astype(str).str.extract('(\d+)')

In [5]:
#處理harddist
df['harddisk'].value_counts() #沒有TB，可以直接處理掉
#1TB=1024GB,1GB=1024MB,1MB=1024KB
#def clean_harddisk(value): 常用的話之後再包成function
df['temp_storage']=df['harddisk'].str.extract('(\d+)').astype(float)
df['temp_storage_2']=df['harddisk'].str.contains('TB',case=False).map({True: 1024, False: 1}).astype(float)
df['harddisk_new_GB']=df['temp_storage']*df['temp_storage_2']
#TEMP可以刪了
df=df.drop(columns=['temp_storage','temp_storage_2'])

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
C:\Users\USER\AppData\Local\Temp\ipykernel_16356\3560972564.py:5: SyntaxWarning: invalid escape sequence '\d'
  df['temp_storage']=df['harddisk'].str.extract('(\d+)').astype(float)

In [6]:
#處理screen_size
df['screen_size'].value_counts()
df['screen_size']=df['screen_size'].astype('str').str.extract('(\d+)')
df['screen_size']=pd.to_numeric(df['screen_size'],errors='coerce')

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\USER\AppData\Local\Temp\ipykernel_16356\1804864438.py:3: SyntaxWarning: invalid escape sequence '\d'
  df['screen_size']=df['screen_size'].astype('str').str.extract('(\d+)')

In [7]:
#檢查missing value
#看一下harddisk是null的資料
missing_value=df[df['harddisk'].isnull()]
print(missing_value)

#看起來有很多NULL 看能不能用相同型號的harddisk補
#所以要先檢查找出同型號中，硬碟容量有幾種不同的值，如果都相同就可以直接補
model_check = df.groupby('model')['harddisk_new_GB'].nunique()
print("同一型號擁有多種硬碟容量的數量：")
print(model_check[model_check > 1].count()) #不行 用填補的

#那只好把price和harddisk、screen_size是null的都刪除
df=df.dropna(subset=['price','harddisk_new_GB','screen_size'])

     brand                   model  screen_size         color harddisk            cpu ram(GB)               OS special_features   graphics     graphics_coprocessor cpu_speed  rating   price currency_symbol  harddisk_new_GB
2      MSI   Vector GP66 12UGS-267         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated                      NaN   1.8 GHz     5.0  1599.0               $              NaN
26    ASUS           ROG Strix G16         16.0  Eclipse Gray      NaN        Core i9      32   Windows 11 Pro              NaN  Dedicated  NVIDIA GeForce RTX 4070   5.6 GHz     4.3  2199.0               $              NaN
27     MSI  Stealth GS66 12UGS-025         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated  NVIDIA GeForce RTX 3070   1.8 GHz     1.0  1699.0               $              NaN
31     MSI   Vector GP66 12UGS-267         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated                      NaN   1.8 GHz     5.0  1599.0               $              NaN
55     MSI  Stealth GS66 12UGS-025         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated  NVIDIA GeForce RTX 3070   1.8 GHz     1.0  1699.0               $              NaN
...    ...                     ...          ...           ...      ...            ...     ...              ...              ...        ...                      ...       ...     ...     ...             ...              ...
4425   MSI  Stealth GS66 12UGS-025         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated  NVIDIA GeForce RTX 3070   1.8 GHz     1.0  1699.0               $              NaN
4438   MSI   Vector GP66 12UGS-267         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated                      NaN   1.8 GHz     5.0  1599.0               $              NaN
4439   MSI  Stealth GS66 12UGS-025         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated  NVIDIA GeForce RTX 3070   1.8 GHz     1.0  1699.0               $              NaN
4440   MSI   Vector GP66 12UGS-267         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated                      NaN   1.8 GHz     5.0  1599.0               $              NaN
4441   MSI  Stealth GS66 12UGS-025         15.0    Core Black      NaN  Intel Core i9      32  Windows 11 Home              NaN  Dedicated  NVIDIA GeForce RTX 3070   1.8 GHz     1.0  1699.0               $              NaN

[576 rows x 16 columns]
同一型號擁有多種硬碟容量的數量：
220

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3857 entries, 0 to 4445
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 3857 non-null   object
 1   model                 2736 non-null   object
 2   screen_size           3857 non-null   float64
 3   color                 3380 non-null   object
 4   harddisk              3857 non-null   object
 5   cpu                   3801 non-null   object
 6   ram(GB)               3803 non-null   object
 7   OS                    3851 non-null   object
 8   special_features      1983 non-null   object
 9   graphics              3824 non-null   object
 10  graphics_coprocessor  2267 non-null   object
 11  cpu_speed             1057 non-null   object
 12  rating                1665 non-null   float64
 13  price                 3857 non-null   float64
 14  currency_symbol       3857 non-null   object
 15  harddisk_new_GB       3857 non-null   float64
dtypes: float64(4), object(12)
memory usage: 512.3+ KB

In [9]:
df.head(12)

    brand          model  screen_size         color harddisk             cpu ram(GB)               OS    special_features    graphics graphics_coprocessor cpu_speed  rating    price currency_symbol  harddisk_new_GB
0    ROKC            NaN         14.0          Blue  1000 GB   Intel Core i7       8       Windows 11                 NaN  Integrated                Intel   1.2 GHz     NaN   589.99               $           1000.0
1      HP            NaN         15.0        Silver  1000 GB   Intel Core i5      64   Windows 11 Pro    Backlit Keyboard  Integrated                Intel       NaN     4.5   999.99               $           1000.0
3   Apple    MacBook Air         13.0        Silver   256 GB         Unknown       8           Mac OS    Backlit Keyboard  Integrated                  NaN       NaN     4.8   689.99               $            256.0
4   Apple    MacBook Air         15.0      Midnight   256 GB         Unknown       8           Mac OS                 NaN  Integrated                  NaN       NaN     4.8  1144.48               $            256.0
5    Acer  A315-24P-R7VH         15.0        Silver   128 GB         Ryzen 3       8     Windows 11 S    Backlit Keyboard  Integrated                  NaN       NaN     4.5   299.99               $            128.0
6   Apple    MacBook Pro         13.0    Space Gray   256 GB         Unknown       8           Mac OS    Backlit Keyboard  Integrated                  NaN       NaN     4.7   965.08               $            256.0
7    Acer      CB315-3HT         15.0        Silver    64 GB   Celeron N4020       4        Chrome OS      Support Stylus  Integrated                  NaN       NaN     4.4   239.99               $             64.0
8    ASUS  ROG Strix G16         16.0  Eclipse Gray   512 GB         Core i7      16  Windows 11 Home    Backlit Keyboard   Dedicated                  NaN       NaN     4.4  1274.03               $            512.0
9    acer   A515-56-347N         15.0        Silver   128 GB  Core I3 1115G4       8     Windows 11 S        Amazon Alexa  Integrated                  NaN       NaN     4.3   299.99               $            128.0
10   acer  AN515-58-57Y8         15.0         Black   512 GB         Core i5      16  Windows 11 Home    Backlit Keyboard   Dedicated                  NaN       NaN     4.4   814.77               $            512.0
11     HP       Notebook         14.0          Grey     1 TB   Ryzen 3 3250U      16       Windows 11  Anti Glare Coating  Integrated                  NaN       NaN     4.4   379.99               $           1024.0
12   ROKC            NaN         15.0          Blue  1152 GB         Pentium      20       Windows 11                 NaN  Integrated                Intel   1.1 GHz     5.0   389.99               $           1152.0

In [10]:
df['brand'].value_counts()

brand
Dell                             1535
HP                                764
ROKC                              637
Lenovo                            265
ASUS                              151
DELL                              146
acer                               95
MSI                                67
LG                                 37
Apple                              22
SAMSUNG                            18
Alienware                          13
Panasonic                          12
Microsoft                          11
Gigabyte                           11
Toughbook                          11
Acer                                9
LENOVO                              6
hp                                  4
Razer                               4
Latitude                            3
lenovo                              3
IVIEW                               2
CTL                                 2
Computer Upgrade King               2
Asus                                2
SHOXLAB                             2
dell                                2
Quality Refurbished Computers       2
Gateway                             2
asus                                1
Tocosy                              1
MAINGEAR                            1
JTD                                 1
GizPro                              1
XAMMUE                              1
MICROTELLA                          1
AWOW                                1
Luqeeg                              1
VAIO                                1
ONN                                 1
Goldengulf                          1
LPT                                 1
Best Notebooks                      1
Corsair                             1
Carlisle FoodService Products       1
Mytrix                              1
Name: count, dtype: int64

In [ ]:
#在進行資料拆分的時候發現有些品牌很小、或者是同品牌大小寫不一致，回來補做清理
#少於一筆的資料拆分會讓上面的程式報錯
#Step 1：統一品牌名稱（先做這個）
df['brand'] = df['brand'].str.lower()
#Step 2：刪掉太少的品牌（關鍵），我選擇刪掉不到三筆的
counts = df['brand'].value_counts()
valid_brands = counts[counts >= 3].index
df = df[df['brand'].isin(valid_brands)]

In [13]:
# 儲存清理好的資料，index=False 是為了不要多出一列沒用的索引序號
df.to_csv('cleaned_laptop_data.csv', index=False, encoding='utf-8-sig')

print("資料清洗完成，已儲存至 cleaned_laptop_data.csv")

資料清洗完成，已儲存至 cleaned_laptop_data.csv